LRA messaging hooks for selected signatures
helidon-io/helidon pull request #2540
Opened 2020-11-20 14:45 UTC by danielkec

Signed-off-by: Daniel Kec <daniel.kec@oracle.com>

2020-11-20 14:53 UTC, danielkec commented on microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/HookTest.java
> +
@paulparkinson Idea is that I am trying to keep context hashmap between channels with Messages itself as keys(so context can be discarded by GC when message is consumed and not referenced any more). It is possible only for some signatures like in the example:
```java 
    @Outgoing("channel1")
    public PublisherBuilder<Message<String>> publish() {
        return ReactiveStreams.of("test1", "test2", "test3")
                .map(Message::of);
    }

    @Incoming("channel1")
    @Outgoing("channel2")
    public String process(String incoming) {
        return incoming.toUpperCase();
    }

    @Incoming("channel2")
    public void consume(String incoming) {
        System.out.println(">>>" + incoming);
    }
```
Output of this POC test look like this:
```
registering
TxId:1 Invoking method process
output org.eclipse.microprofile.reactive.messaging.Message$1@4ebea12c
TxId:1 Invoked method process
TxId:2 Invoking method consume
>>>TEST1
output org.eclipse.microprofile.reactive.messaging.Message$1@44c79f32
TxId:2 Invoked method consume
TxId:3 Invoking method process
output org.eclipse.microprofile.reactive.messaging.Message$1@757d6814
TxId:3 Invoked method process
TxId:4 Invoking method consume
>>>TEST2
output org.eclipse.microprofile.reactive.messaging.Message$1@649725e3
TxId:4 Invoked method consume
TxId:5 Invoking method process
output org.eclipse.microprofile.reactive.messaging.Message$1@4c168660
TxId:5 Invoked method process
TxId:6 Invoking method consume
>>>TEST3
output org.eclipse.microprofile.reactive.messaging.Message$1@52b56a3e
TxId:6 Invoked method consume
```

2020-11-20 15:19 UTC, danielkec commented on microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/HookTest.java
> +
hm its not right

2020-11-23 13:01 UTC, tomas-langer requested changes

2020-11-23 13:01 UTC, tomas-langer commented on microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/HookTest.java
> +        System.out.println("registering");
Please remove all instances of `System.out.println` from your code. Even in tests.

2020-11-26 04:10 UTC, paulparkinson approved these changes
yes, this should do the trick.

2021-02-12 03:39 UTC, paulparkinson approved these changes
I have confirmed this is working well and can be merged when ready.  Thanks!

2021-02-16 22:47 UTC, paulparkinson approved these changes

2021-03-18 03:53 UTC, paulparkinson submitted a review, later dismissed
this works well, thanks

2021-04-06 11:46 UTC, tomas-langer requested changes

2021-04-06 11:46 UTC, tomas-langer commented on messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/JmsConnector.java
> +                            jmsMessage = ((OutgoingJmsMessageImpl<?>) m).toJmsMessage(session, mapper.get());
Seems like a brave cast - are we 100% sure this is our implementation?

2021-04-06 11:46 UTC, tomas-langer commented on microprofile/messaging/core/src/main/java/io/helidon/microprofile/messaging/AbstractMessagingMethod.java
> +    public String getName() {
Why are these methods changed to `public`? Also if this is expected to be exposed by a `public` subclass, please add javadocs.

2021-04-06 11:46 UTC, tomas-langer commented on microprofile/messaging/core/src/main/java/io/helidon/microprofile/messaging/MessageContext.java
> +public class MessageContext extends ConcurrentHashMap<String, Object> {
Extending a map is not recommended in general. This is a strange construct - is there a design document that would explain this class and its usage?

2022-10-03 19:57 UTC, romain-grecourt commented
closing for inactivity

2022-10-03 19:57 UTC, closed without merging