4.x features
helidon-io/helidon pull request #5549
Opened 2022-11-29 10:45 UTC by tomas-langer

New feature API, processor and catalog.

See docs-internal/feature-catalog.md for details about changes.

- introduces `@Aot` annotation to define whether native image is supported (or to add description with limitations)
- introduces `@Incubating` for features that are to stay with Helidon, but are in the progress of shaping their APIs
- introduces `@Experimenta` for features that may be removed, or heavily modified
- introduces `@Feature` as the feature definition

All of these annotations are to be used on `module-info.java` module definition

2022-11-29 14:13 UTC, m0mus commented
What's the difference between `@Incubating` and `@Experimental`. I am not convinced that we need `@Experimental` as it's described. Can you provide some samples?

2022-11-30 15:12 UTC, barchetta requested changes

2022-11-30 16:17 UTC, tomas-langer commented on common/features/api/src/main/java/io/helidon/common/features/api/Experimental.java
> + * Experimental module may be changed including backward incompatible changes in between major versions of Helidon.
So have `Preview` and `Experimental`, or `Preview` and `Incubating`? 
I would try to keep only two of these

2022-11-30 16:53 UTC, barchetta commented on common/features/api/src/main/java/io/helidon/common/features/api/Experimental.java
> + * Experimental module may be changed including backward incompatible changes in between major versions of Helidon.
I am proposing "Preview" and "Incubating".

2022-11-30 18:01 UTC, tomas-langer commented on common/features/api/src/main/java/io/helidon/common/features/api/Experimental.java
> + * Experimental module may be changed including backward incompatible changes in between major versions of Helidon.
OK, I will refactor the PR

2022-12-06 11:59 UTC, tomas-langer commented
Rebased to resolve conflict

2022-12-07 11:03 UTC, tomas-langer commented
> What's the difference between `@Incubating` and `@Experimental`. I am not convinced that we need `@Experimental` as it's described. Can you provide some samples?

Updated description of PR with examples

2022-12-12 21:47 UTC, barchetta commented on common/features/api/src/main/java/io/helidon/common/features/api/Incubating.java
> + * Incubating features may be changed including backward incompatible changes in between major versions of Helidon.
"between major versions of Helidon" -> "between any version of Helidon"

2022-12-12 21:47 UTC, barchetta commented on common/features/api/src/main/java/io/helidon/common/features/api/Preview.java
> + * Preview feature may be changed including backward incompatible changes in between major versions of Helidon.
Maybe change "major" to "minor"? We allow API changes for any API between major versions.  I think we should have a bit more flexibility with Preview APIs.

2022-12-13 16:59 UTC, barchetta approved these changes

2022-12-13 17:19 UTC, merged