Observe log
helidon-io/helidon pull request #5656
Opened 2022-12-13 18:34 UTC by tomas-langer

Observe log:
 - read log levels of loggers
 - configure log levels of loggers
 - read log stream
 - protected endpoints (even when security not configured)
Observe config:
- protected endpoints

A few related changes required for all of this to work correctly.

Resolves: 5426
Resolves: 5655

2022-12-14 15:24 UTC, danielkec requested changes

2022-12-14 15:24 UTC, danielkec commented on nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/HttpRouting.java
>           * @param maxReRouteCount
```suggestion
         * @param maxReRouteCount maximum number of allowed re-routes
```

2022-12-15 16:21 UTC, danielkec approved these changes

2022-12-16 12:01 UTC, Verdent approved these changes

2022-12-16 12:39 UTC, tomas-langer commented on examples/nima/observe/src/main/java/io/helidon/examples/nima/observe/ObserveMain.java
> +        //.error(UnauthorizedException.class, (req, res, throwable) -> res.status(NOT_FOUND_404).send());
Fixed

2022-12-16 12:40 UTC, Verdent submitted a review, later dismissed

2022-12-16 17:19 UTC, tomas-langer commented
Rebased on top of main to fix intermittent failure

2022-12-16 17:20 UTC, danielkec approved these changes

2022-12-16 17:55 UTC, merged