[2.x] OpenApi Generator examples
helidon-io/helidon pull request #5722
Opened 2022-12-19 17:19 UTC by aserkes

[2.x] backport for OpenApi Generator examples

2023-02-22 16:56 UTC, tjquinno requested changes
We should change the Helidon version as noted (because I'm so late reviewing this).

2023-02-22 16:56 UTC, tjquinno commented on examples/openapi-tools/quickstart-mp/README.md
> +          -p helidonVersion=2.5.2 \
Please change to 2.5.6 (the now-current release).

2023-02-22 16:56 UTC, tjquinno commented on examples/openapi-tools/quickstart-mp/README.md
> +          -p helidonVersion=2.5.2 \
2.5.6

2023-02-22 16:56 UTC, tjquinno commented on examples/openapi-tools/quickstart-mp/mp-client/pom.xml
> +        <version>2.5.2</version>
2.5.7-SNAPSHOT

By changing the versions in the ``pom files to this, they will automatically be updated with each new release. Then we would just need to update the release in the readme files manually. I am seeing if there is a good way to update those automatically as well.. But not necessarily as part of this PR.

2023-02-22 16:56 UTC, tjquinno commented on examples/openapi-tools/quickstart-mp/mp-server/pom.xml
> +        <version>2.5.2</version>
2.5.7-SNAPSHOT

2023-02-22 16:56 UTC, tjquinno commented on examples/openapi-tools/quickstart-se/se-client/pom.xml
> +        <version>2.5.2</version>
2.5.7-SNAPSHOT

2023-02-22 16:56 UTC, tjquinno commented on examples/openapi-tools/quickstart-se/se-server/pom.xml
> +        <version>2.5.2</version>
2.5.7-SNAPSHOT

2023-02-24 08:36 UTC, merged

2023-02-24 20:28 UTC, Captain1653 commented
I can be wrong, but there are many wrong copyrights in this PR. 
<img width="1708" alt="Screenshot 2023-02-24 at 22 24 38" src="https://user-images.githubusercontent.com/4740207/221284767-eb5a6339-0fb9-48b1-a10f-40635f3ee547.png">

2023-02-27 23:55 UTC, romain-grecourt commented
@Captain1653 This is the PR was created in 2022 and merged in 2023.