Doc updates for Jaeger tracing port value
helidon-io/helidon pull request #6060
Opened 2023-02-02 19:17 UTC by ljamen

Doc for issue #5187

2023-02-02 19:19 UTC, ljamen commented
Hi @tjquinno  - There are a couple of ways to address this doc bug. I believe you were asking the team how to update. Did you get your answer?

Should the doc contain a brief note at least listing these and/or explaining workarounds if any? For example, propagation is no longer supported, but propagation: b3 is no longer needed because the Helidon's JaegerTracerBuilder class always includes the OpenTelemetry B3Propagator.

2023-02-02 21:49 UTC, tjquinno commented
TBH I am not sure what workarounds, if any, are available for the settings that Jaeger no longer supports. Our config properties, then and now, simply mirror whatever Helidon's code can set on Jaeger's span exporter builder. Jaeger changed and so the settings we can expose changed as well.

Given that, it's probably clearer to _not_ list the specific settings we _no longer_ support (given that, at least at the moment, I don't know what, if any, workaround there might be). Maybe, just before the `include` of the generated config `.adoc` file, we could state something like this:

> Because Jaeger changed its client implementation some Jaeger settings exposed by earlier releases of Helidon are no longer available. Please note the currently-supported settings in the table below.

or something to that effect.

2023-02-02 21:52 UTC, tjquinno requested changes

2023-02-02 21:52 UTC, tjquinno commented on docs/config/io_helidon_tracing_jaeger_JaegerTracerBuilder.adoc
> +    Copyright (c) 2023 Oracle and/or its affiliates.
Do not change this file (or any in the `docs/config` directory) manually.

They are all generated.

2023-02-02 21:52 UTC, tjquinno commented on docs/includes/tracing/tracer-jaeger.adoc
See my comment in the PR discussion for a suggested brief note to insert here.

2023-02-02 21:52 UTC, tjquinno commented on docs/se/tracing.adoc
> +For Web Server we have a path-based support for configuring tracing, in addition
Very small. Maybe remove the "a" from before "path-based" here?

2023-02-07 15:08 UTC, al3xandru commented
This commit doesn't include a fix for https://helidon.io/docs/v3/#/se/guides/tracing (the snippet using private void getDefaultMessageHandler refers to and uese the io.opentracing instead of io.helidon.tracing API)

2023-02-07 15:12 UTC, ljamen commented
Hi @al3xandru I'm working with Tim on that. This is still in draft mode until I've completed all of the updates. They will be included in this PR.

2023-02-07 21:27 UTC, ljamen commented
Closing this PR and will include files in a new PR that does not include the generated tracing doc that was accidentally updated.

2023-02-07 21:27 UTC, closed without merging