Security rework synchronous
helidon-io/helidon pull request #6230
Opened 2023-02-16 10:29 UTC by Verdent

2023-06-07 12:46 UTC, tomas-langer requested changes

2023-06-07 12:46 UTC, tomas-langer commented on security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcUtil.java
> +                //TODO Níma client tracing
Tracing is ready

2023-06-07 12:46 UTC, tomas-langer commented on security/providers/oidc/pom.xml
> +<!--        <dependency>-->
remove commented out text

2023-06-08 10:31 UTC, Verdent commented on security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcUtil.java
> +//                .relativeUris(relativeUris);
Fixed

2023-06-08 10:31 UTC, Verdent commented on security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcUtil.java
> +                //TODO Níma client tracing
Fixed

2023-06-08 10:32 UTC, Verdent commented on security/providers/oidc/pom.xml
> +<!--        <dependency>-->
fixed

2023-06-08 11:09 UTC, Verdent commented on security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/Tenant.java
> +            //TODO Níma client security?
Follow up issue https://github.com/helidon-io/helidon/issues/6967

2023-06-08 11:13 UTC, Verdent commented
Created two follow up issues: https://github.com/helidon-io/helidon/issues/6967 and https://github.com/helidon-io/helidon/issues/6968

2023-06-08 16:38 UTC, tomas-langer commented on security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperProvider.java
> +    private final AppTokenRx appToken;
`AppTokenRx` name should not be used.

2023-06-08 16:44 UTC, Verdent commented on security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperProvider.java
> +    private final AppTokenRx appToken;
fixed

2023-06-08 16:44 UTC, tomas-langer approved these changes

2023-06-09 07:54 UTC, merged