[3.x] OIDC original uri resolving leaving out query params
helidon-io/helidon pull request #6342
Opened 2023-03-02 17:01 UTC by Verdent

Fixes #6341

2023-03-02 17:49 UTC, danielkec requested changes

2023-03-02 17:49 UTC, danielkec commented on security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
> +            }
Could it be?
```suggestion
            URI uri = providerRequest.env().targetUri();
            String query = uri.getQuery();
            String path = uri.getPath();

            if ((null != query) && !query.isEmpty()) {
                origUri = List.of(path + "?" + query);
            } else {
                origUri = List.of(path);
            }
```

2023-03-07 14:08 UTC, danielkec submitted a review, later dismissed

2023-03-07 14:09 UTC, spericas commented on security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
> +            }
`(null != query)` -> query != null

2023-03-09 14:42 UTC, danielkec approved these changes

2023-03-09 14:58 UTC, merged