Use GitHub Action for helidon-3.x branch
helidon-io/helidon pull request #6500
Opened 2023-03-28 14:08 UTC by tvallin

If the changes are approved, I will create the follow up issues for the tests I disabled.

Description of tests failures:

   - `.../examples/faulttolerance/MainTest#testTimeout`
 ```
 Error:  io.helidon.webserver.examples.faulttolerance.MainTest.testTimeout  Time elapsed: 0.643 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <408 Request Timeout>
     but: was <200 OK>
	at io.helidon.webserver.examples.faulttolerance.MainTest.testTimeout(MainTest.java:196)
```

   - `OpentraceableClientE2ETest#e2e`
```
Error: OpentraceableClientE2ETest.e2e:114
Expected: a collection with size <0>
but: collection size was <1>
```

   - `.../integration/webclient/MutualTlsTest#testNoClientCert`
```
Error: io.helidon.tests.integration.webclient.MutualTlsTest.testNoClientCert Time elapsed: 0.13 s <<< FAILURE!

java.lang.AssertionError:

Expected: a string containing "Received fatal alert: bad_certificate"
but: was "(client reqID: 54) Connection reset by the host"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at io.helidon.tests.integration.webclient.MutualTlsTest.testNoClientCert(MutualTlsTest.java:86)
```

2023-03-28 16:11 UTC, tomas-langer requested changes
The failing tests are ok in 4.x, so probably some changes were not backported to 3.x

2023-03-28 16:11 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +      - name: JLink packaging
This is missing native image packaging tests

2023-03-30 13:00 UTC, tvallin commented
Copyright is failing because changes made to a file were reverted. If you are okay with the final changes, I will squash the commit and copyright check should pass.

2023-03-31 19:40 UTC, tomas-langer requested changes

2023-03-31 19:40 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +  build:
I am missing spotbugs

2023-03-31 19:40 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +  tck:
is this running an TCK other than MP TCK? If not, which is it in a different place and called differently than in `main`?

2023-03-31 19:40 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +      - uses: graalvm/setup-graalvm@v1
This sets up both graalvm and Java. This is confusing, and I am not sure which JDK would be used

2023-03-31 19:40 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +  build:
Also missing docs build

2023-03-31 19:40 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +  tck:
OK, so it is only runnin gthe reactive streams TCK, but not MP TCK. MP TCK is a must during build as well

2023-03-31 19:44 UTC, tomas-langer requested changes

2023-03-31 19:44 UTC, tomas-langer commented on .github/workflows/validate.yaml
> +        run: etc/scripts/test-packaging-native.sh
All these scripts do a priming build, which should be done just once (through `githbug-compile.sh`), it can be removed from all of them.

2023-04-14 20:13 UTC, tomas-langer submitted a review, later dismissed

2023-04-17 17:41 UTC, romain-grecourt approved these changes

2023-04-17 17:44 UTC, merged