Validate http request headers when using the webclient
helidon-io/helidon pull request #6515
Opened 2023-03-30 00:09 UTC by klustria

2023-03-30 00:11 UTC, klustria commented
This PR is a potential fix for https://github.com/helidon-io/helidon/issues/6338

2023-04-05 20:03 UTC, Verdent commented
I feel like it is OK, but I would like to know also your opinion @tomas-langer

2023-04-06 08:13 UTC, tomas-langer requested changes

2023-04-06 08:13 UTC, tomas-langer commented on nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
> +    private static void validateHeaderValues(HeaderValue header) throws IllegalArgumentException {
I think that this method may be better suited to `HeaderValue` directly, as it represents an HTTP Header value, and the same rules apply to any version of HTTP I think.
Then we could use the same validation logic regardless of server/client

2023-06-21 17:03 UTC, klustria commented
Please check the description section of this issue to see the list of items that are included in the change.

2023-06-22 11:31 UTC, tomas-langer reviewed
We should not do the change in `LazyString`
I think validation should be done once for all headers after they are read from the stream (both on server and on client when enabled).
We could add `HeaderValue.validate(Validator)` method - and make it work nicely with multi-valued headers in the right way, rather then attempting to target `LazyString` specifically

2023-06-26 05:48 UTC, klustria commented
> We should not do the change in `LazyString`
> I think validation should be done once for all headers after they are read from the stream (both on server and on client when enabled).
> We could add `HeaderValue.validate(Validator)` method - and make it work nicely with multi-valued headers in the right way, rather then attempting to target `LazyString` specifically

With the new change, removed response header validation from LazyString and placed it in Http1HeaderParser.readHeaders after a header's name and value are parsed and using the same Http.HeaderValue.validate() that HttpCallChainBase.writeHeaders() uses to validate both the header name/values for the request Headers. Also remove name token validation in Http1HeaderParser.readHeaderName() as the name is already validated in Http.HeaderValue.validate().

2023-06-28 09:44 UTC, tomas-langer approved these changes

2023-06-28 15:18 UTC, merged