Add configuration support for EXECUTOR_SHUTDOWN_MILLIS
helidon-io/helidon pull request #6955
Opened 2023-06-06 14:20 UTC by Tomas-Kraus

PR #6822 is included.
Added few lines to connect this PR with WebServer configuration and tests to make sure it works.

2023-07-21 12:11 UTC, Tomas-Kraus commented
Fixed main conflicts for the 2nd time.

2023-07-24 12:03 UTC, tomas-langer requested changes

2023-07-24 12:03 UTC, tomas-langer commented on nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ListenerConfigBlueprint.java
> +    long shutdownGracePeriod();
All timeouts/times should use `Duration`

2023-07-27 17:25 UTC, tomas-langer approved these changes

2023-07-27 18:42 UTC, merged