2.x: Fix #5877: native-image warnings after Netty upgrade
helidon-io/helidon pull request #7087
Opened 2023-06-24 16:56 UTC by barchetta

2023-06-26 18:09 UTC, romain-grecourt approved these changes

2024-01-18 14:34 UTC, tomas-langer requested changes
sorry, requires copyright updates

2024-04-08 20:09 UTC, romain-grecourt approved these changes

2024-04-08 20:11 UTC, barchetta commented
> sorry, requires copyright updates

Fixed

2024-04-08 22:21 UTC, merged