Client URL scheme validation #6547
helidon-io/helidon pull request #7475
Opened 2023-08-27 09:27 UTC by danielkec

Fixes #6547

2023-08-31 16:11 UTC, tomas-langer requested changes
As per our direct messages:
The `ClientUri` represents a URI (that should be used regardless of protocol.
The validation is a function of the client request in use - so WebSocket client should validate ws, wss, http, https; Http based web clients should validate `http, https` etc.

2023-09-05 09:48 UTC, tomas-langer commented on webclient/websocket/src/test/java/io/helidon/webclient/websocket/WsClientTest.java
> +        try {
Use `assertThrows` instead

2023-09-05 09:48 UTC, tomas-langer commented on webclient/websocket/src/test/java/io/helidon/webclient/websocket/WsClientTest.java
> +public class WsClientTest {
Do not use `public`

2023-09-05 15:19 UTC, danielkec commented on webclient/websocket/src/test/java/io/helidon/webclient/websocket/WsClientTest.java
> +        try {
fixed

2023-09-05 15:20 UTC, danielkec commented on webclient/websocket/src/test/java/io/helidon/webclient/websocket/WsClientTest.java
> +public class WsClientTest {
fixed

2023-09-05 17:59 UTC, tomas-langer approved these changes

2023-09-05 18:00 UTC, merged