Support Jersey Multipart feature by Helidon Connector
helidon-io/helidon pull request #7652
Opened 2023-09-22 16:58 UTC by jansupol

Jersey multipart feature updates the headers just before the first write of entity takes place. This PR is to reflect this change in CONTENT-TYPE header before the `WebClientBuilder` submits the entity.

Fixes the `User-Agent` HTTP header value.

2023-09-24 12:35 UTC, danielkec requested changes

2023-09-24 12:35 UTC, danielkec commented on jersey/connector/src/test/java/io/helidon/jersey/connector/MultipartTest.java
> +    }
Please use `@RepeatedTest` or `@ParameterizedTest` with `@EnumSource` 
```suggestion
    @ParameterizedTest
    @EnumSource(value = HelidonEntity.HelidonEntityType.class)
    void testMultipart(HelidonEntity.HelidonEntityType entityType, WebTarget webTarget) {
        // For each entity type
        // make 10 consecutive requests
        for (int i = 0; i != 10; i++) {
            MultiPart multipart = new MultiPart().bodyPart(new BodyPart().entity(ENTITY));
            multipart.setMediaType(MediaType.MULTIPART_FORM_DATA_TYPE);
            try (Response r = ClientBuilder.newBuilder()
                    .property(HelidonConnector.INTERNAL_ENTITY_TYPE, entityType.name())
                    .build().target(webTarget.getUri())
                    .path("upload")
                    .register(MultiPartFeature.class)
                    .request()
                    .post(Entity.entity(multipart, multipart.getMediaType()))) {
                Assertions.assertEquals(Response.Status.OK.getStatusCode(), r.getStatus());
                Assertions.assertEquals(ENTITY, r.readEntity(String.class));
            }
        }
    }
```

2023-09-24 12:35 UTC, danielkec commented on jersey/connector/pom.xml
> +        </dependency>
Cdi and jersey server should be transitive iirc
```suggestion
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.tests</groupId>
            <artifactId>helidon-microprofile-tests-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.server</groupId>
            <artifactId>helidon-microprofile-server</artifactId>
            <scope>test</scope>
        </dependency>
```

2023-10-23 12:30 UTC, danielkec approved these changes

2024-02-22 18:05 UTC, romain-grecourt approved these changes

2024-02-22 18:17 UTC, merged