Upgrade to Microstream 08.01.01-MS-GA and other minor things
helidon-io/helidon pull request #7752
Opened 2023-10-08 22:18 UTC by hrstoyanov

@barchetta @hg-ms 
Please consider this Microstream 08.01.01-MS-GA (latest official release) upgrade to Helidon 4. 

Summary of changes:
- Enforced Java 17 Microstream enhancements.
- Could not re-write 1 test case , commented it out. Maybe @hg-ms   can take a look at it.
- Fixed other small useful things for this extension that IntelliJ found.

I was able to run the test cases.

2023-10-08 22:29 UTC, hrstoyanov commented
I signed the Contributor Agreement. Jeez .. hire more developers Oracle, not lawyers!

2023-10-09 14:56 UTC, barchetta commented
@hrstoyanov thank you for your contribution! We will review.

2023-10-09 15:28 UTC, barchetta reviewed
See copyright check for a list of files that need the copyright updated. And thanks for your contribution and patience with our lawyers!

2023-10-09 15:28 UTC, barchetta commented on dependencies/pom.xml
> +                <version>1.1.1</version>
You should not need to explicitly include this dependency. It is a transitive dependency of `microstream-cache`.  I was able to build your PR without expressing this dependency. So please remove it from here and from `integrations/microstream/cache/pom.xml`

2023-10-09 15:28 UTC, barchetta commented on integrations/microstream/cache/pom.xml
> +        </dependency>
You should be able to remove this. See previous comment.

2023-10-09 20:37 UTC, hrstoyanov commented
@barchetta , I just committed the requested changes, let me know if you have further requests.
@hg-ms last chance to review before this gets merged!

2023-10-09 23:01 UTC, tjquinno requested changes
There are several files where you have changed only the copyright date. We avoid that if we can, although sometimes it's necessary if a file was changed, pushed, and then the change reverted.

2023-10-10 03:06 UTC, hrstoyanov commented on integrations/microstream/metrics/src/main/java/io/helidon/integrations/microstream/metrics/MicrostreamMetricsSupport.java
> +    //static final String BASE_ENABLED_KEY = CONFIG_METRIC_ENABLED_VENDOR + "enabled";
Done

2023-10-10 03:38 UTC, barchetta commented
@hrstoyanov one more copyright fix needed. Almost there!

2023-10-10 07:22 UTC, tvallin commented
The PR should not contains file where copyright are changed and no other changes were made to the file. 
I understand the copyright check is failing and the reason is what @tjquinno explained during is review. To fix that, you can squash your commits and force-push. In this way, you will pass the copyright check without updating copyright to unchanged files.

2023-10-10 14:17 UTC, barchetta approved these changes
LGTM. Many thanks.

2023-10-10 14:20 UTC, tjquinno approved these changes

2023-10-10 14:22 UTC, merged

2023-10-14 00:39 UTC, hrstoyanov commented
@fh-ms - please review.

2023-10-17 05:48 UTC, hg-ms commented
@hrstoyanov 
FH is currently out of office, so I had a look at the merged PR.
I have no objections, the code looks fine.

Many thanks from the Microstream team for the version upgrade.
Best regards.