4.x: Graceful client connection close
helidon-io/helidon pull request #7973
Opened 2023-11-08 09:20 UTC by danielkec

Fixes part of #6545

2023-11-20 16:33 UTC, tomas-langer requested changes

2023-11-21 07:26 UTC, danielkec commented on webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnection.java
> +        this.goAway(0, Http2ErrorCode.NO_ERROR, "Closing connection");
Ah I see the goaway

2023-11-21 07:34 UTC, closed without merging

2023-11-21 07:41 UTC, danielkec commented on webclient/api/src/main/java/io/helidon/webclient/spi/ClientConnectionCache.java
> +        Runtime.getRuntime()
huh thx!

2023-11-21 12:04 UTC, danielkec commented on webclient/api/src/main/java/io/helidon/webclient/api/LoomClient.java
> +                cl.releaseResource();
cool