2.x: 7110 Bad media type log level
helidon-io/helidon pull request #8031
Opened 2023-11-17 17:38 UTC by danielkec

Fixes #7110

2023-11-20 16:21 UTC, tomas-langer requested changes
See notes for 3.x

2024-01-08 19:14 UTC, tomas-langer submitted a review, later dismissed
looks good, but copyright

2024-02-21 19:16 UTC, romain-grecourt approved these changes

2024-02-21 20:28 UTC, tomas-langer approved these changes

2024-02-22 18:04 UTC, merged