[WIP] 4.x: 8059 Delayed fixed rate scheduling
helidon-io/helidon pull request #8075
Opened 2023-11-24 13:56 UTC by danielkec

Fixes #8059

2023-12-08 14:48 UTC, tomas-langer requested changes

2023-12-12 16:40 UTC, danielkec commented on scheduling/src/main/java/io/helidon/scheduling/FixedRateConfigBlueprint.java
> +    long delay();
It's a legacy api we have since Helidon 2, we can do a breaking change for the next major version

2023-12-12 16:40 UTC, danielkec commented on scheduling/src/main/java/io/helidon/scheduling/FixedRateConfigBlueprint.java
> +    @Option.DefaultCode("@io.helidon.scheduling.FixedRate.DelayType@.SINCE_PREVIOUS_START")
fixed

2023-12-12 16:41 UTC, danielkec commented on scheduling/src/main/java/io/helidon/scheduling/FixedRateConfigBlueprint.java
> +    TimeUnit timeUnit();
fixed

2023-12-12 16:41 UTC, danielkec commented on scheduling/src/main/java/io/helidon/scheduling/FixedRateConfigBlueprint.java
> +    TimeUnit timeUnit();
https://github.com/helidon-io/helidon/pull/8075#discussion_r1424287232

2023-12-12 23:06 UTC, tomas-langer approved these changes

2023-12-13 08:12 UTC, merged