TLS Revocation config
helidon-io/helidon pull request #8425
Opened 2024-02-27 16:19 UTC by Verdent

### Description

Fixes #8321 

### Documentation

Generated documentation added

2024-03-01 22:10 UTC, romain-grecourt reviewed
Adding generated config documentation is not enough.
Can you provide a simplified usage example ?

2024-03-07 15:19 UTC, tomas-langer requested changes

2024-03-07 15:19 UTC, tomas-langer commented on common/tls/src/main/java/io/helidon/common/tls/ConfiguredTlsManager.java
> +    protected void initializeTmf(TrustManagerFactory tmf, KeyStore keyStore, TlsConfig tlsConfig)
`protected` should have javadoc.

2024-03-07 15:19 UTC, tomas-langer commented on common/tls/src/main/java/io/helidon/common/tls/ConfiguredTlsManager.java
> +    protected void initializeTmf(TrustManagerFactory tmf, KeyStore keyStore, TlsConfig tlsConfig)
This method should not throw checked exceptions (to be consistent with other methods in this class)

2024-03-07 15:19 UTC, tomas-langer commented on common/tls/src/main/java/io/helidon/common/tls/RevocationConfigBlueprint.java
> +interface RevocationConfigBlueprint {
Missing class javadoc.

2024-03-07 15:19 UTC, tomas-langer commented on common/tls/src/main/java/io/helidon/common/tls/RevocationConfigBlueprint.java
> +     * @return whether to prefer CRL over OCSP
would be nice to have a bit of explanation of what `CRL` and `OCSP` is (ie. CRL is a link to list of revoked certificates, OCSP is an endpoint to validate specific certificate)

2024-03-07 15:19 UTC, tomas-langer commented on common/tls/src/main/java/io/helidon/common/tls/RevocationConfigBlueprint.java
> +     * Enable fallback to the less preferred checking option.
Is this related to CRL and OCSP? If so, it should be mentioned

2024-03-07 15:19 UTC, tomas-langer commented on integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/DefaultOciCertificatesTlsManager.java
> +            throw new RuntimeException(e);
RuntimeException should not be used, but I see it is used in other methods...

2024-03-07 15:19 UTC, tomas-langer commented on tests/integration/tls-revocation-config/src/test/resources/logging.properties
> +sun.security.provider.certpath.level=FINEST
this (FINEST or FINER log levels) should not be enabled in repo, please either comment out or remove

2024-03-07 16:35 UTC, tomas-langer approved these changes

2024-03-11 20:00 UTC, merged