4.x: add helidon-logging-jul as a test dependency to some modules #7799
helidon-io/helidon pull request #8804
Opened 2024-05-27 11:37 UTC by jbescos

### Description

https://github.com/helidon-io/helidon/issues/7799

### Documentation

N/A

2024-05-28 11:32 UTC, tomas-langer requested changes

2024-05-28 11:32 UTC, tomas-langer commented on common/testing/junit5/pom.xml
> +        <dependency>
This does not make sense here - there is no `logging.properties`, so the logging is not required.

2024-05-28 11:32 UTC, tomas-langer commented on common/testing/junit5/pom.xml
> +        <dependency>
As the issue describes, this should only be added to modules that use our appender. Please make sure that is the case for all added dependencies.

2024-05-29 09:57 UTC, jbescos commented
I'm starting from scratch in other PR

2024-05-29 09:57 UTC, closed without merging