Issue #7102 - WebClient should have a mode that is resilient to bad media/content types
helidon-io/helidon pull request #9040
Opened 2024-07-26 11:46 UTC by Tomas-Kraus

fixes issue #7102
backport of issue #6774 fix

2024-07-26 12:44 UTC, Verdent requested changes
I have a 2 questions. :-)
1. Why have you decided to drop ParserMode enum, which was used in the 4.x implementation?
2. I think I have not seen it also in the 4.x version, but should not these relaxed formats of the content types be also configurable? I mean if user wants to add their own.

2024-07-26 12:44 UTC, Verdent commented on tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
> +                    .await();
Please set timeout to the await method.

2024-07-26 12:44 UTC, Verdent commented on tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
> +                .await();
add timeout please.

2024-07-26 12:44 UTC, Verdent commented on tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
> +                .await();
add timeout please.

2024-07-26 12:44 UTC, Verdent commented on tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
> +    private static final String INVALID_CONTENT_TYPE_VALUE = "invalid header value";
constants should be at the top of the class.

2024-07-26 12:44 UTC, Verdent commented on tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
> +    private static void invalidContentType(ServerRequest request, ServerResponse response) {
Move also these static methods under the beforeAll method please. I could not find them when trying to figure out what the endpoint does.

2024-07-26 12:44 UTC, Verdent commented on tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
> +        client.get()
I think this formatting should be padded.

2024-07-26 14:18 UTC, Tomas-Kraus commented
>     1. Why have you decided to drop ParserMode enum, which was used in the 4.x implementation?
MediaType in 4.x is rewritten. It's parse method is not public so changing prototype did not cause any issues.
MediaType parse method in 3.x is public static and as I understand it properly, it shall match current prototype to be used as method reference. That's the reason why I made it without ParserMode enum and mode is choosen by the method being called.

>     2. I think I have not seen it also in the 4.x version, but should not these relaxed formats of the content types be also configurable? I mean if user wants to add their own.
4.x version has hard-coded relaxed format as well. I made it the way jeff requested. This issue is just backport, not any additional enhancement to be done in 3.x only.

2024-07-29 14:24 UTC, tomas-langer approved these changes

2024-07-29 14:35 UTC, Verdent approved these changes

2024-07-30 09:22 UTC, merged