Helidon Builder docs
helidon-io/helidon pull request #9544
Opened 2024-11-29 16:01 UTC by m0mus

### Description

Documentation for Helidon Builder feature.

2024-12-09 21:53 UTC, tomas-langer requested changes

2025-01-08 11:11 UTC, m0mus commented on docs/src/main/asciidoc/se/builder.adoc
> +        return create(ServiceConfig.builder()
Right. I used `Retry` as a reference and it's done this way there:

```
    /**
     * Create a new retry with customized configuration.
     *
     * @param builderConsumer consumer of builder
     * @return a new retry customized through builder
     */
    static Retry create(Consumer<RetryConfig.Builder> builderConsumer) {
        return create(RetryConfig.builder()
                              .update(builderConsumer)
                              .buildPrototype());
    }
```

2025-01-08 11:46 UTC, m0mus commented on docs/src/main/asciidoc/se/builder.adoc
> +        return create(ServiceConfig.builder()
I updated it as you suggested anyway.

2025-01-16 12:39 UTC, tomas-langer approved these changes

2025-02-05 09:06 UTC, merged